  
name: .NET Core

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
env:
  SolutionFile: 'src\SellerCloud.Results.sln'
  
jobs:
  build:

    runs-on: [self-hosted, windows]

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build
      run: dotnet build ${{env.SolutionFile}} /clp:ErrorsOnly --configuration Release --no-restore
