name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  SolutionFile: 'src\SellerCloud.Results.sln'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Install dependencies
      run: dotnet restore './src/SellerCloud.Results.sln' /clp:ErrorsOnly
    - name: Build
      run: dotnet build './src/SellerCloud.Results.sln' /clp:ErrorsOnly --configuration Release --no-restore
