name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.103
    - name: Restore dependencies
      run: dotnet restore ./src/SellerCloud.Results /clp:ErrorsOnly
    - name: Restore packages
      run: nuget restore ./src/SellerCloud.Results
    - name: Build
      run: dotnet build "SellerCloud.Results.csproj" --framework netcoreapp3.0 --no-restore ./src
